#!/bin/sh -u

cd "${0%/*}"

ret="$(osascript -e 'display dialog "input server ip address or play offline"¬
buttons {"Offline", "OK"} default button "OK" default answer "127.0.0.1"')"

start_server=""

if $(echo "$ret" | grep -q Offline); then
	start_server="1"
	ip="127.0.0.1"
else
	ip=$(echo "$ret" | sed 's/.*text returned:\(.*\)$/\1/g')
fi

if [ -n "$start_server" ]; then
	./crtsd $RANDOM&
	pid=$!
fi

./crts -s "$ip" -oopengl -i2 -k../Resources/cfg/keymap.ini

if [ -n "$start_server" ]; then
	kill "$pid"
fi
