#!/bin/sh -u

die() {
	echo "$@" >&2
	exit 1
}

exe="${MESON_INSTALL_PREFIX}/Contents/MacOS/client"

olib="$(otool -L "$exe" | grep glfw | cut -f 2 | cut -d ' ' -f 1)"
bundled_lib="$olib"
test -n "$olib" || die "failed to get lib"

if [ -s "$olib" ]; then
	echo "dereferencing symlink"

	while true; do
		oolib="$olib"
		olib="$(readlink "$olib")"

		if [ ! -f "$olib" ]; then
			olib="$(dirname "$oolib")/$olib"
		fi

		echo "-> $olib"

		if [ -f "$olib" ]; then
			break
		elif [ ! -s "$olib" ]; then
			die "failed to dereference"
		fi
	done
elif [ ! -f "$olib" ]; then
	die "'$olib' is not a file or a symlink"
fi

echo "determined lib path: '$olib'"

set -e

mkdir -vp ${MESON_INSTALL_PREFIX}/Contents/lib
cp -v "$olib" ${MESON_INSTALL_PREFIX}/Contents/lib

install_name_tool -change "$bundled_lib" \
	@executable_path/../lib/"$(basename "$olib")" \
	"$exe"
