# this file ends in .yaml so that builds.sr.ht won't pick it up

version: '{build}'
branches:
  only:
  - master
clone_depth: 1
environment:
  MOCHIRO_UPLOAD_KEY:
    secure: /tdmrVEDkJA6xAnNSjfUiw72/xDX5MLAPrGfRFm+Fy8=
  matrix:
  - job_name: Windows
    appveyor_build_worker_image: Visual Studio 2019
  - job_name: macOS
    appveyor_build_worker_image: macOS-Mojave
for:
-
  matrix:
    only:
      - job_name: Windows
  build_script:
    - ps: |
        meson `
          --buildtype=release `
          "-Dtargets=tests,server,client,terragen" `
          -Duis=opengl `
          -Dpackaging=windows `
          -Dembed_assets=true `
          -Dupload=true `
          build
        meson compile -C build
        meson test -C build
        meson install -C build
-
  matrix:
    only:
      - job_name: macOS
  build_script:
    - sh: |
        set -eux
        HOMEBREW_NO_AUTO_UPDATE=1 brew install meson imagemagick
        meson \
          --buildtype=release \
          -Dtargets=tests,server,client,terragen \
          -Duis=opengl \
          -Dpackaging=macos \
          -Dembed_assets=true \
          -Dupload=true \
          build
        meson compile -C build
        meson test -C build
        meson install -C build
