# this file ends in .yaml so that builds.sr.ht won't pick it up

version: '{build}'
branches:
  only:
  - master
clone_depth: 1
environment:
  BINTRAY_API_KEY:
    secure: ckcdmldKubphOxRHf4SzciFju+hSzclmPObOaNbosAaZW6taRdXioIcU+HWeDF9f
  matrix:
  - job_name: Windows
    appveyor_build_worker_image: Visual Studio 2019
  - job_name: macOS
    appveyor_build_worker_image: macOS-Mojave
for:
-
  matrix:
    only:
      - job_name: Windows
  build_script:
    - ps: C:\cygwin64\bin\sh.exe C:\projects\crts\bin\makecygwin
-
  matrix:
    only:
      - job_name: macOS
  build_script:
    - sh: |
        set -eux
        HOMEBREW_NO_AUTO_UPDATE=1 brew install meson glfw imagemagick

        export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig

        bin/makemacos build

        ver="$(bin/version)"
        bintray="https://api.bintray.com/content/annacrombie/crts/crts"

        curl -T crts.app.zip \
          -uannacrombie:$BINTRAY_API_KEY \
          "$bintray/${ver}/crts.app.${ver}.zip?publish=1&override=1"
