#!/usr/bin/env python3

import os
import shutil
import sys

dirs = {}
dirs["binaries"] = sys.argv[1]
dirs["resources"] = os.path.join(dirs["binaries"], "resources")

app = {
    "binaries": [],
    "resources": [],
}

for arg in sys.argv[2:]:
    if arg == "-b":
        l = app["binaries"]
    elif arg == "-r":
        l = app["resources"]
    else:
        l.append(arg)

if os.path.exists(dirs["binaries"]):
    shutil.rmtree(dirs["binaries"])

for d in dirs.values():
    os.mkdir(d)

for d in app:
    for e in app[d]:
        shutil.copy(e, os.path.join(dirs[d], os.path.basename(e)))
