#!/bin/sh -eu

exec 2>&1

printf "HTTP/1.0 200 OK\nContent-type: text/html\n\n"

printf '<html>
<head>
        <meta charset="UTF-8">
        <title>crts - ci</title>
        <link rel="stylesheet" type="text/css" href="style.css">
        <style>
                pre {
                        white-space: normal;
                        text-align: left;
                }

                pre code {
                        display: inline-block;
                        text-align: left;
                        padding: 0px 1em 1em 1em;
                        white-space: pre-line;
                }
        </style>
</head>
<body>
<img src="https://mochiro.moe/crts/assets/status.svg"></img>
<h2><a href="https://mochiro.moe/crts">return</a></h2>
<h2>build.log</h2>
'

printf '<pre><code>'
cat /git/crts/build.log
printf '</code></pre>'

printf '</body>
</html>
'
