#!/usr/bin/env python3

import sys
import urllib.request
import zipfile
import io

url = sys.argv[1]
outdir = sys.argv[2]
response = urllib.request.urlopen(url)
data = io.BytesIO(response.read())

with zipfile.ZipFile(data, compression=zipfile.ZIP_DEFLATED) as z:
    for f in z.infolist():
        z.extract(f, path=outdir)
