#!/bin/sh

# this script gets called by powershell on the windows appveyor build
# see: .builds/appveyor.yaml

# stderr messes up powershell, so redirect it to stdout
exec 2>&1

set -eux

build=build
install=crts_windows
buildtype=release

# install packages
curl -sO https://www.cygwin.com/setup-x86_64.exe

export PATH="/usr/local/bin:/usr/bin"

./setup-x86_64.exe -q -P meson,gcc,zip

# build

meson \
	--buildtype=release \
	-Dtargets=tests,server,client,terragen \
	-Duis=opengl \
	-Dpackaging=windows \
	-embed_assets=true \
	-Dupload=true \
	build

ninja -C "$build" test install
