#!/bin/sh -eu

build=$1
app=crts.app
buildtype=release

rm -rf "$app"
rm -rf "$build"

meson setup \
	--prefix="$PWD/$app" \
        --bindir=Contents/MacOS \
        -Dsubcmd-dir=Contents/MacOS \
	-Dbuild-tests=true \
	-Dopengl-ui=true \
	-Dncurses-ui=disabled \
	-Dbuild-server=false \
	-Dbuild-launcher=false \
	-Dbuild-macos-app=true \
	--buildtype="$buildtype" \
        $build

ninja -C "$build" test install

zip -r ${app}.zip $app
