#!/bin/sh

# this script gets called by powershell on the windows appveyor build
# see: .builds/appveyor.yaml

# stderr messes up powershell, so redirect it to stdout
exec 2>&1

set -eux

build=build
install=crts_windows
buildtype=release

# install packages
curl -sO https://www.cygwin.com/setup-x86_64.exe

export PATH="/usr/local/bin:/usr/bin"

./setup-x86_64.exe -q -P meson,gcc,zip

# build

meson --prefix="$PWD/$install" \
	--bindir="$PWD/$install" \
	--buildtype="$buildtype" \
	-Dopengl-ui=true \
	-Dncurses-ui=disabled \
	-Dbuild-launcher=false \
	-Dbuild-tests=true \
	-Dsubcmd-dir="$PWD/$install" \
	$build

ninja -C "$build" test install

ver="$(build_util/scripts/version)"
bintray="https://api.bintray.com/content/annacrombie/crts/crts"

cp /bin/cygwin1.dll "$install"
zip -r "${install}.zip" "$install"

set +x
curl -T "${install}.zip" \
	-uannacrombie:$BINTRAY_API_KEY \
	"$bintray/${ver}/${install}.${ver}.zip?publish=1&override=1"
