#!/usr/bin/env python3

import hashlib
import os
import sys

from urllib.request import (
    Request,
    HTTPPasswordMgrWithDefaultRealm,
    HTTPBasicAuthHandler,
    build_opener,
    install_opener,
    urlopen,
)

source_file = sys.argv[1]
dest_file = os.path.basename(source_file)

headers = {"Content-type": "application/octet-stream"}
url = f"https://mochiro.moe/crts/upload"

pass_manager = HTTPPasswordMgrWithDefaultRealm()
pass_manager.add_password(None, url, "crts-upload", os.environ["MOCHIRO_UPLOAD_KEY"])

auth_handler = HTTPBasicAuthHandler(pass_manager)
opener = build_opener(auth_handler)

install_opener(opener)

with open(source_file, "rb") as f:
    src = f.read()

digest = hashlib.sha256(src).hexdigest()

res = urlopen(
    Request(
        url + f"?{dest_file}&{digest}",
        data=src,
        headers=headers,
        method="PUT",
    )
)

print(f"{res.status} {res.reason}: " + res.read().decode("utf-8"))
