#!/usr/bin/env python3

from zipfile import ZipFile, ZIP_DEFLATED
import os
import sys
import glob

dest_file = sys.argv[1]
cmdline_sources = sys.argv[2:]
sources = []


def strip_prefix(s, prefix):
    if s.startswith(prefix):
        return s[len(prefix) :]
    else:
        return s


if len(cmdline_sources) == 1 and os.path.isdir(cmdline_sources[0]):
    base = cmdline_sources[0]
    trim = os.path.dirname(base)
    for f in glob.iglob(os.path.join(base, "**"), recursive=True):
        sources.append((f, strip_prefix(f, trim)))
else:
    for f in cmdline_sources:
        if os.path.isdir(f):
            raise Exception(f"{f} is a directory")
        sources.append((f, os.path.basename(f)))

if not sources:
    raise Exception("no sources for zip")

with ZipFile(dest_file, mode="w", compression=ZIP_DEFLATED) as myzip:
    for (s, n) in sources:
        myzip.write(s, arcname=n)
